%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 387.10403428641712
Camera.fy: 384.91587525758240
Camera.cx: 316.90526764041016
Camera.cy: 183.63322815723933

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0

Camera.width: 640
Camera.height: 360

# Camera frames per second 
Camera.fps: 30.0

# stereo baseline times fx
Camera.bf: 60.207

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 35

#--------------------------------------------------------------------------------------------
# Stereo Rectification. Only if you need to pre-rectify the images.
# Camera.fx, .fy, etc must be the same as in LEFT.P
#--------------------------------------------------------------------------------------------
LEFT.height: 360
LEFT.width: 640
LEFT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data:[ -3.5877230839179701e-02, 1.2017526854112015e-01,
       -3.1946701109838904e-01, 2.4927139833207484e-01, 0.0 ]
LEFT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 3.8710403428641712e+02, 0., 3.1690526764041016e+02, 0.,
       3.8491587525758240e+02, 1.8363322815723933e+02, 0., 0., 1. ]
LEFT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.9879966577457646e-01, 4.0858252361038648e-02,
       -2.7015381962800594e-02, -4.1892807757828728e-02,
       9.9836425796152428e-01, -3.8907596727383066e-02,
       2.5381495360989621e-02, 3.9992644810474140e-02,
       9.9887755408473544e-01 ]
LEFT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [ 3.2316085880250370e+02, 0., 3.3248974641506027e+02, 0., 0.,
       3.2316085880250370e+02, 1.9981898818434536e+02, 0., 0., 0., 1.,
       0. ]

RIGHT.height: 480
RIGHT.width: 752
RIGHT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ -2.1685267237365816e-03, -7.3664178262961233e-02,
       1.1546962400030557e-01, -7.9165202802951251e-02, 0.0 ]
RIGHT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 3.8556741375813073e+02, 0., 3.2233736626269075e+02, 0.,
       3.8394240982156333e+02, 2.1258991769936074e+02, 0., 0., 1. ]
RIGHT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.9899236159575788e-01, 4.0968926403518402e-02,
       -1.8325079608926962e-02, -4.0213672631228971e-02,
       9.9839650976945093e-01, 3.9840554886784910e-02,
       1.9927920283832039e-02, -3.9063491261300071e-02,
       9.9903799809799021e-01 ]
RIGHT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [ 3.2316085880250370e+02, 0., 3.3248974641506027e+02,
       -1.9476449692399207e+01, 0., 3.2316085880250370e+02,
       1.9981898818434536e+02, 0., 0., 0., 1., 0. ]

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize:2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500

